### ISSUE TITLE
Newbie Question (I'm sorry)

### ISSUE THREAD

**Issue by Flashpok** [antanasbruzas/abNinjam#18]
Hi,
I discover the Linux World. I use Reaninjam (Reaper) since years on Macbook. 
I want to try your abNinjam on linux (Bitwig studio, linux mint 20.1) but I m a newbie in Terminal.
I tried your code lines but... I'm wrong.
Can you explain how can I build and make and use :-) your Ninjam plugin ?

First step OK but second step NOT OK: git submodule update --init
Can you be more specific ? When I try this command, I'm wrong.
Sorry for this newbie question, but I want so try your plugin :-) 
Thank you

EDIT: Sorry, I find the VST Releases. It works ! Thank you for your work !

**Comment by antanasbruzas** [comment]
I'm glad that you got it working :)
